import { AifchemStreamEvent } from "../aifchem/types.js";

const DATA_FENCE_START = "```data";
const CODE_FENCE_END = "```";
const DEFAULT_DISCLAIMER = "This answer is generated by a Large Language Model, please verify the information independently.";

export interface AssistantSanitizeOptions {
  stripUiPayloads?: boolean;
  stripDisclaimers?: boolean;
}

function safeJsonParse<T>(text: string): T | undefined {
  try {
    return JSON.parse(text) as T;
  } catch {
    return undefined;
  }
}

export function extractEventObjectsFromChunkBuffer(buffer: string): {
  rest: string;
  events: AifchemStreamEvent[];
} {
  const events: AifchemStreamEvent[] = [];
  let remaining = buffer;

  const sseBlocks = remaining.split("\n\n");
  if (sseBlocks.length > 1) {
    remaining = sseBlocks.pop() ?? "";
    for (const block of sseBlocks) {
      const dataLines = block
        .split("\n")
        .filter((line) => line.startsWith("data:"))
        .map((line) => line.slice(5).trim())
        .filter(Boolean);

      for (const data of dataLines) {
        if (data === "[DONE]") {
          events.push({ done: true });
          continue;
        }
        const parsed = safeJsonParse<AifchemStreamEvent>(data);
        if (parsed) {
          events.push(parsed);
        }
      }
    }
    return { rest: remaining, events };
  }

  const jsonLines = remaining.split("\n");
  if (jsonLines.length > 1) {
    remaining = jsonLines.pop() ?? "";
    for (const line of jsonLines.map((value) => value.trim()).filter(Boolean)) {
      const parsed = safeJsonParse<AifchemStreamEvent>(line);
      if (parsed) {
        events.push(parsed);
      }
    }
  }

  return { rest: remaining, events };
}

export function extractTextFromAifchemEvent(event: AifchemStreamEvent): {
  cumulative?: string;
  delta?: string;
  done?: boolean;
} {
  if (event.done) {
    return { done: true };
  }
  if (typeof event.delta === "string") {
    return { delta: event.delta };
  }
  if (typeof event.text === "string") {
    return { delta: event.text };
  }
  if (typeof event.content === "string") {
    return { cumulative: event.content };
  }
  return {};
}

function longestSuffixPrefixLength(value: string, prefix: string): number {
  const maxLength = Math.min(value.length, prefix.length - 1);
  for (let length = maxLength; length > 0; length -= 1) {
    if (value.slice(-length) === prefix.slice(0, length)) {
      return length;
    }
  }
  return 0;
}

export class DataFenceFilter {
  private mode: "normal" | "in_data_fence" = "normal";
  private pending = "";

  push(chunk: string): string {
    let output = "";

    for (const char of chunk) {
      const marker = this.mode === "normal" ? DATA_FENCE_START : CODE_FENCE_END;
      const candidate = this.pending + char;

      if (marker.startsWith(candidate)) {
        this.pending = candidate;
        if (candidate === marker) {
          this.pending = "";
          this.mode = this.mode === "normal" ? "in_data_fence" : "normal";
        }
        continue;
      }

      const keepLength = longestSuffixPrefixLength(candidate, marker);
      const flush = candidate.slice(0, candidate.length - keepLength);
      this.pending = candidate.slice(candidate.length - keepLength);

      if (this.mode === "normal") {
        output += flush;
      }
    }

    return output;
  }

  flush(): string {
    if (this.mode === "normal") {
      const remaining = this.pending;
      this.pending = "";
      return remaining;
    }

    this.pending = "";
    return "";
  }
}

export function sanitizeAssistantContent(text: string, options: AssistantSanitizeOptions = {}): string {
  const stripUiPayloads = options.stripUiPayloads !== false;
  const stripDisclaimers = options.stripDisclaimers !== false;
  const sanitized = stripUiPayloads ? (() => {
    const filter = new DataFenceFilter();
    return filter.push(text) + filter.flush();
  })() : text;
  const withoutDisclaimers = stripDisclaimers ? sanitized.replaceAll(DEFAULT_DISCLAIMER, "") : sanitized;

  return withoutDisclaimers
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}
